FROM ruby:3.4.2 AS builder

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs npm

RUN npm install -g yarn

COPY backend/Gemfile* ./

RUN bundle install --jobs=4

FROM ruby:3.4.2-slim

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install -y libpq-dev nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bundle /usr/local/bundle

COPY backend .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]