services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - backend_bundle:/usr/local/bundle
      - backend_tmp:/app/tmp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: ${DATABASE_URL}
      TZ: ${TZ}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "8000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000/api
    command: npm run dev

volumes:
  mysql_data:
  backend_bundle:
  frontend_node_modules:
  backend_tmp:
