version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: app_production
    restart: always

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:${DB_PASSWORD}@db/app_production
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  mysql_data: