source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.2'

gem 'rails', '~> 7.1.0'
gem 'mysql2', '~> 0.5.5'
gem 'puma', '~> 6.0'
gem 'bootsnap', '>= 1.4.4', require: false  

gem 'rack-cors'
gem 'jbuilder', '~> 2.11'
# gem 'fast_jsonapi'

# gem 'devise'
# gem 'jwt'
# gem 'pundit'

# バックグラウンド処理
# gem 'sidekiq'

# 監視・ロギング
gem 'lograge'
# gem 'sentry-ruby'
# gem 'prometheus-client'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rubocop-rails', require: false
  gem 'brakeman', require: false
  gem 'dotenv-rails'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.7'
  gem 'spring'
  gem 'annotate'
  gem 'bullet'
  gem 'solargraph', require: false
end

group :test do
  gem 'shoulda-matchers', '~> 5.0'
  gem 'simplecov', require: false
  gem 'database_cleaner-active_record'
  gem 'webmock'
  gem 'vcr'
end